#!/usr/bin/env bash

# The following installs two files that patch problems with
# atom's REPL package.
#
echo "CSCI 1103 setup - patch atom's REPL package. NB: this script"
echo "cannot be executed until atom AFTER is installed and atom's"
echo "REPL package is installed."

cp ./replOcaml.js $HOME/.atom/packages/Repl/Repls/
cp ./ReplView.coffee $HOME/.atom/packages/Repl/lib/Repl-View/

echo "CSCI 1103 patchREPL - done."
